	.CR 6800               ; LOAD MC6800 CROSS OVERLAY
	.TF ttt.exe,BIN        ; OUTPUT FILE IN BINARY FORMAT
	.OR $0200              ; START OF ASSEMBLY ADDRESS
	.LI OFF                ; SWITCH OFF ASSEMBLY LISTING (EXCEPT ERRORS)
	.SF SYMBOLS.SYM        ; CREATE SYMBOL FILE
;	NAM HELP
;	Options set in file override command line option settings.
;	OPT	c		* options must be in lower case
;	OPT	cre		* one option per line
;	ORG	$0
DIDDLE	.EQU	$F0A2
DISBUF	.EQU	$E41D
MNPTR	.EQU	$E419
PUT		.EQU	$F0BB


BEG	LDX	#$7679		"HE"
	STX	DISBUF		STORE TO FIRST 2 DISPLAYS
	LDX	#$3873		"LP"
	STX	DISBUF+2
	LDX	#$4040		"--"
	STX	DISBUF+4	STORE THE LAST 2 DISPLAY
	LDX	#DIDDLE		ADDR OF DIDDLE ROUTINE
	STX	MNPTR		ESTABLISH AS ACTIVE SUB OF PUT
	JMP	PUT		CALL DISPLAY ROUTINE
